server:
  port: 7000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: mail-service
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27018/?authSource=admin
      database: mail-db
  mail:
    host: smtp.gmail.com
    port: 587
    username: school.mailspring@gmail.com
    password: zrytdlyaojafcrrr
    properties.mail.smtp:
      auth: true
      starttls.enable: true